name: Lapse CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Rubocop
        run: bundle exec rubocop

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [checks]

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOSTNAME }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/lapse
            git pull
            /home/volchok/.rbenv/shims/bundle install
            /home/volchok/.rbenv/shims/rails db:migrate
            /home/volchok/.rbenv/shims/rails assets:precompile
            sudo service apache2 restart
